### ISSUE TITLE
issue getting started

### ISSUE THREAD

**Issue by angusdavison** [HKyleZhang/RecView#1]
Hi Hongkai  - I am aiming to finely map recombination breakpoints in a bunch of snails and so was glad to find your software. However, I am having a  few issues getting started with the test data set. Hopefully, the queries are rather obvious and the solution is straightforward. Updated both R and Rstudio to most recent versions (4.4.1 and 2024/04/2 build 764)

I loaded the test data and saved as csv (though I could not get make_012gt to write directly so imported as df and then saved as csv). I launched the app and selected the csv and scaffold file, selected one individual and also one chromosome, then pressed "Run". I get the following error. Something wrong, looking in wrong location?

Thanks - I have a bunch of other questions but will leave them until after I have been able to try my own data :)

Angus
----
Listening on http://127.0.0.1:3289
New names:                                                                                                          
• `` -> `...1`
                                                                                                                    
 ------------------------------
 Note: There are 8 cores available.
 The analysis is run on 1 cores.
 ------------------------------

Warning: Error in {: task 1 failed - "could not find function "rec_analyse""
  3: shiny::runApp
  2: shiny::runGadget
  1: run_RecView_App

**Comment by HKyleZhang** [comment]
Hi Angus,
Thank you for posting the issue! It is likely the error occurred when the app performed parallelisation with foreach but without the rec_analyse function properly distributed, for which I've modified the codes in the app. Please reinstall the package and give an another try. :)

**Comment by angusdavison** [comment]
OK, thanks! I reinstalled. That problem has now gone, and I get the following error:

Warning: Error in {: task 1 failed - "Can't select columns that don't exist.
✖ Column `A` doesn't exist."
  3: shiny::runApp
  2: shiny::runGadget
  1: run_RecView_App[](url)

In case an issue, pasting the first few lines of the csv:

id,CHROM,POS,Aarun_V9-73,Aarun_H7-41,Aarun_H5-17,Aarun_H0-81,Aarun_H7-38,Aarun_H3-00,ID-256,ID-258
Contig108:12447,Contig108,12447,1,0,0,0,0,0,0,0
Contig108:51178,Contig108,51178,0,1,0,0,1,0,0,0
Contig108:68848,Contig108,68848,1,0,0,0,1,0,0,0
Contig108:78063,Contig108,78063,0,1,0,1,0,0,0,0
Contig108:90409,Contig108,90409,1,0,0,0,1,0,0,0
Contig108:99792,Contig108,99792,0,0,0,0,1,0,0,0

**Comment by HKyleZhang** [comment]
This is about the column names not recognised by the app. Because different datasets may have different labels for the grandparents and parents, the function _make_012gt_ is designed to essentially rename the columns into "A" "B" "C" "D" "AB" "CD" for the app, and converts the genotypes (e.g. 0/1) into 012 format (e.g. 1 represents 0/1). 

With your csv, the genotypes are completely converted, but the column names need to be renamed so that the column of paternal grandfather is renamed to "A", paternal grandmother "B", maternal grandfather "C", maternal grandmother "D", father "AB", mother "CD". 

From the column names I guess you are trying with the paper's dataset. In this case, Aarun_V9-73 is the maternal grandfather, Aarun_H7-41 is the maternal grandmother, Aarun_H5-17 is mother, Aarun_H0-81 is paternal grandmother, Aarun_H7-38 is paternal grandfather, Aarun_H3-00 is father. So the heading of your csv file should be "id,CHROM,POS,C,D,CD,B,A,AB,ID-256,ID-258".

When you have the genotype file generated by using vcftools, I suggest to use _make_012gt_ for the formating (Workflow A in README). In the function arguments, "gt" is path to the genotype file, "F0F1_rename" is where you give a character variable telling the labels for the grandparents in parents (the order is always paternal grandfather, paternal grandmother, maternal grandfather, maternal grandmother, father, mother), "save_filename" is the filename you want to designate for the file to be saved, and the file will be saved in your current working directory.

**Comment by angusdavison** [comment]
OK, got it - now working! I made an error in the syntax of the make_012gt command. This worked, rearranging and relabelling the columns:

make_012gt("1percent_downsampled_dataset.GT", c("Aarun_H7-38","Aarun_H0-81","Aarun_V9-73","Aarun_H7-41","Aarun_H3-00","Aarun_H5-17"), "test1.txt")

--
id,CHROM,POS,A,B,C,D,AB,CD,ID-256,ID-258
Contig108:12447,Contig108,12447,0,0,1,0,0,0,0,0
Contig108:51178,Contig108,51178,1,0,0,1,0,0,0,0
Contig108:68848,Contig108,68848,1,0,1,0,0,0,0,0
Contig108:78063,Contig108,78063,0,1,0,1,0,0,0,0
Contig108:90409,Contig108,90409,1,0,1,0,0,0,0,0
Contig108:99792,Contig108,99792,1,0,0,0,0,0,0,0
