### ISSUE TITLE
inbreeding

### ISSUE THREAD

**Issue by angusdavison** [HKyleZhang/RecView#2]
Hi Hongkai

so far RecView is working great with my data I think it is going to be an invaluable resource for me. 

I do have a slight issue in that the parents (AB, CD) are full-siblings, so that there are only two grandparents rather than four. I dealt with this in a first run by duplicating the data for the two grandparents - but of course in consequence the GoO inference shows nothing useful. Nonetheless, the output in terms of breakpoints seems to make sense in terms of what I already knew (especially using CCS). Question would be to ask if there is a more sensible way to deal with this? I am not sure if that is easy (or possible) to implement?

Angus

**Comment by HKyleZhang** [comment]
Hi Angus,
Glad to hear RecView can be helpful!

Duplicating the data of grandparents for the analysis makes sense because the case of full-sib parents can be considered as a special case where two pairs of grandparents have the same unphased genotypes? The number of informative sites can be expected to be fewer though, i.e. only the sites where the grandparents are respective homozygous for reference and alternate alleles will be useful.

With fewer informative sites, GoO inference should still show something like, for example in paternal chromosome, some alleles in a region are assigned to PGF and some other alleles in the next region are assigned to PGM? Such a switching point between two regions indicates a recombination, and PD or CCS enables to pinpoint this switching location. 

With fewer informative sites, PD may need to use a smaller _radius_ because it checks this number of snps in flanking regions at each _step_ moving along the chromosome.

**Comment by angusdavison** [comment]
OK, got it thanks!
